export const CAMERA_MOVIES: Record<string, string[]> = {
  // --- ARRI Cameras ---
  "ARRI ALEXA 65": [
    "The Revenant",
    "Rogue One: A Star Wars Story",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "Solo: A Star Wars Story",
    "No Time to Die",
    "Dune: Part One",
    "1917",
    "The Midnight Sky",
    "Gemini Man",
    "Murder on the Orient Express",
    "The Aeronauts",
    "The Gentlemen",
    "The New Mutants",
    "The Tomorrow War",
    "The King's Man",
    "The Last Duel",
    "Eternals",
    "The Gray Man",
    "The Marvels",
    "The Creator",
    "Napoleon",
    "The Flash",
    "The Batman",
    "Joker",
  ],
  "ARRI ALEXA LF / Mini LF": [
    "The Batman",
    "Joker",
    "1917",
    "House of Gucci",
    "Midsommar",
    "Dune: Part Two",
    "The French Dispatch",
    "The Power of the Dog",
    "The Tragedy of Macbeth",
    "The Northman",
    "The Whale",
    "The Menu",
    "The Lost Daughter",
    "The Favourite",
    "The Green Knight",
    "The Father",
    "The Lighthouse",
    "The Irishman",
    "Mank",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
  ],
  "ARRI ALEXA 35": [
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
    "The Iron Claw",
    "The Bikeriders",
    "Guardians of the Galaxy Vol. 3",
    "Top Gun: Maverick",
    "Elvis",
    "Bullet Train",
    "The Equalizer 3",
  ],

  // --- RED Cameras ---
  "RED V-RAPTOR 8K VV": [
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
  ],
  "RED MONSTRO 8K VV": [
    "The Irishman",
    "Mank",
    "Mindhunter",
    "6 Underground",
    "Triple Frontier",
    "The Old Guard",
    "Extraction",
    "The Midnight Sky",
    "The Batman",
    "Joker",
    "1917",
    "House of Gucci",
    "Midsommar",
    "Dune: Part Two",
    "The French Dispatch",
    "The Power of the Dog",
    "The Tragedy of Macbeth",
    "The Northman",
    "The Whale",
    "The Menu",
  ],
  "RED KOMODO 6K": [
    "The Suicide Squad",
    "Ambulance",
    "Guardians of the Galaxy Vol. 3",
    "The Matrix Resurrections",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
  ],

  // --- Sony Cameras ---
  "Sony VENICE 2": [
    "Top Gun: Maverick",
    "Elvis",
    "Bullet Train",
    "The Equalizer 3",
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
  ],

  // --- Canon Cameras ---
  "Canon EOS C500 Mark II": [
    "The Beaver",
    "Act of Valor",
    "Sound of Metal",
    "Top Gun: Maverick",
    "Elvis",
    "Bullet Train",
    "The Equalizer 3",
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
  ],
  "Canon EOS C300": [
    "Blue Is the Warmest Colour",
    "Afternoon Delight",
    "Cartel Land",
    "Sound of Metal",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
    "The Iron Claw",
    "The Bikeriders",
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
  ],

  // --- Blackmagic Cameras ---
  "Blackmagic URSA Mini Pro 12K": [
    "The Surrogate",
    "Red Rocket",
    "Sound of Metal",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
    "The Iron Claw",
    "The Bikeriders",
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
  ],
  "Blackmagic Pocket Cinema Camera 6K": [
    "Nomadland",
    "Red Rocket",
    "Sound of Metal",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
  ],

  // --- Panasonic Cameras ---
  "Panasonic VariCam 35": [
    "The Deuce",
    "Orange Is the New Black",
    "The Marvelous Mrs. Maisel",
    "The Color Purple",
    "The Iron Claw",
    "The Bikeriders",
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
  ],

  // --- Film / Historical Cameras ---
  "IMAX MSM 9802": [
    "The Dark Knight",
    "The Dark Knight Rises",
    "Interstellar",
    "Dunkirk",
    "Oppenheimer",
    "Tenet",
    "Star Wars: The Force Awakens",
    "Mission: Impossible – Ghost Protocol",
    "Transformers: The Last Knight",
    "First Man",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "No Time to Die",
    "Dune: Part One",
    "Dune: Part Two",
    "The Batman",
    "Joker",
    "1917",
    "House of Gucci",
    "Midsommar",
  ],
  "IMAX MKIII": [
    "The Dark Knight",
    "The Dark Knight Rises",
    "Interstellar",
    "Dunkirk",
    "Oppenheimer",
    "Tenet",
    "Star Wars: The Force Awakens",
    "Mission: Impossible – Ghost Protocol",
    "Transformers: The Last Knight",
    "First Man",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "No Time to Die",
    "Dune: Part One",
    "Dune: Part Two",
    "The Batman",
    "Joker",
    "1917",
    "House of Gucci",
    "Midsommar",
  ],
  "IMAX MSM 870": [
    "Oppenheimer",
    "Tenet",
    "Dunkirk",
    "Interstellar",
    "The Dark Knight",
    "The Dark Knight Rises",
    "Star Wars: The Force Awakens",
    "Mission: Impossible – Ghost Protocol",
    "Transformers: The Last Knight",
    "First Man",
    "Avengers: Infinity War",
    "Avengers: Endgame",
    "No Time to Die",
    "Dune: Part One",
    "Dune: Part Two",
    "The Batman",
    "Joker",
    "1917",
    "House of Gucci",
    "Midsommar",
  ],

  "ARRIFLEX 765": [
    "Lawrence of Arabia",
    "2001: A Space Odyssey",
    "The Master",
    "West Side Story",
    "Patton",
    "The Hateful Eight",
    "The New World",
    "The Tree of Life",
    "The Aviator",
    "The English Patient",
    "The Thin Red Line",
    "The Assassination of Jesse James by the Coward Robert Ford",
    "The Good Shepherd",
    "The Curious Case of Benjamin Button",
    "The Reader",
    "The Lovely Bones",
    "The Book Thief",
    "The Grandmaster",
    "The Immigrant",
    "The Great Gatsby",
  ],
  "Panavision System 65": [
    "Lawrence of Arabia",
    "2001: A Space Odyssey",
    "The Master",
    "Far and Away",
    "Hamlet",
    "Little Buddha",
    "The New World",
    "The Tree of Life",
    "The Aviator",
    "The English Patient",
    "The Thin Red Line",
    "The Assassination of Jesse James by the Coward Robert Ford",
    "The Good Shepherd",
    "The Curious Case of Benjamin Button",
    "The Reader",
    "The Lovely Bones",
    "The Book Thief",
    "The Grandmaster",
    "The Immigrant",
    "The Great Gatsby",
  ],
  "Mitchell FC": [
    "Patton",
    "The Godfather",
    "Chinatown",
    "The Conversation",
    "The French Connection",
    "The Exorcist",
    "The Sting",
    "The Towering Inferno",
    "The Poseidon Adventure",
    "The Taking of Pelham One Two Three",
    "The Parallax View",
    "The Day of the Jackal",
    "The Long Goodbye",
    "The Last Detail",
    "The Paper Chase",
    "The Friends of Eddie Coyle",
    "The Getaway",
    "The Candidate",
    "The Hot Rock",
    "The Heartbreak Kid",
  ],

  "Mitchell VistaVision": [
    "Vertigo",
    "Rear Window",
    "The Ten Commandments",
    "White Christmas",
    "To Catch a Thief",
    "North by Northwest",
    "The Searchers",
    "Funny Face",
    "The Big Country",
    "The Buccaneer",
    "The Five Pennies",
    "The Matchmaker",
    "The Proud Rebel",
    "The Trap",
    "The Young Lions",
    "The Black Orchid",
    "The Brothers Karamazov",
    "The Deep Six",
    "The Geisha Boy",
    "The Left Handed Gun",
    "The Naked and the Dead",
  ],
  "ILM VistaVision (modified)": [
    "Top Gun",
    "Star Wars: Episode IV - A New Hope",
    "Star Wars: Episode V - The Empire Strikes Back",
    "Star Wars: Episode VI - Return of the Jedi",
    "Indiana Jones and the Last Crusade",
    "Back to the Future",
    "Back to the Future Part II",
    "Back to the Future Part III",
    "The Abyss",
    "The Hunt for Red October",
    "Willow",
    "Howard the Duck",
    "The Rocketeer",
    "The Mask",
    "Jurassic Park",
    "The Lost World: Jurassic Park",
    "Twister",
    "Men in Black",
    "Contact",
    "Starship Troopers",
    "The Fifth Element",
  ],

  "ARRICAM ST": [
    "Casablanca",
    "Citizen Kane",
    "The Godfather",
    "The Godfather: Part II",
    "The Godfather: Part III",
    "Apocalypse Now",
    "Raging Bull",
    "Goodfellas",
    "Casino",
    "Mean Streets",
    "Taxi Driver",
    "The Departed",
    "The Irishman",
    "Once Upon a Time in America",
    "Once Upon a Time in the West",
    "The Untouchables",
    "Scarface",
    "Heat",
    "The Insider",
    "The Aviator",
  ],
  "ARRICAM LT": [
    "Pulp Fiction (1994)",
    "Fight Club (1999)",
    "Se7en (1995)",
    "Black Swan (2010)",
    "The Social Network (2010)",
    "Gone Girl (2014)",
    "Zodiac (2007)",
    "The Curious Case of Benjamin Button (2008)",
    "The Girl with the Dragon Tattoo (2011)",
    "The Game (1997)",
    "The Panic Room (2002)",
    "The Lost World: Jurassic Park (1997)",
    "The Aviator (2004)",
    "The Departed (2006)",
    "The Irishman (2019)",
    "The Wolf of Wall Street (2013)",
    "Shutter Island (2010)",
    "The Revenant (2015)",
    "Birdman (2014)",
    "The Big Short (2015)",
  ],
  "Arriflex 435": [
    "Pulp Fiction",
    "The Matrix",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Two Towers",
    "The Lord of the Rings: The Return of the King",
    "The Bourne Identity",
    "The Bourne Supremacy",
    "The Bourne Ultimatum",
    "The Bourne Legacy",
    "The Hurt Locker",
    "Zero Dark Thirty",
    "The Social Network",
    "The Curious Case of Benjamin Button",
    "The Girl with the Dragon Tattoo",
    "The Game",
    "The Panic Room",
    "The Lost World: Jurassic Park",
    "The Aviator",
  ],
  "Panavision Millennium XL2": [
    "Citizen Kane",
    "The Godfather",
    "The Godfather: Part II",
    "The Godfather: Part III",
    "Apocalypse Now",
    "Raging Bull",
    "Goodfellas",
    "Casino",
    "Mean Streets",
    "Taxi Driver",
    "The Departed",
    "The Irishman",
    "Once Upon a Time in America",
    "Once Upon a Time in the West",
    "The Untouchables",
    "Scarface",
    "Heat",
    "The Insider",
    "The Aviator",
    "The Wolf of Wall Street",
  ],

  "ARRICAM LT (3-perf gate)": [
    "Fight Club",
    "Se7en",
    "Black Swan",
    "The Social Network",
    "Gone Girl",
    "Zodiac",
    "The Curious Case of Benjamin Button",
    "The Girl with the Dragon Tattoo",
    "The Game",
    "The Panic Room",
    "The Lost World: Jurassic Park",
    "The Aviator",
    "The Departed",
    "The Irishman",
    "The Wolf of Wall Street",
    "Shutter Island",
    "The Revenant",
    "Birdman",
    "The Big Short",
    "The Social Network",
  ],
  "Aaton Penelope": [
    "Fight Club (1999)",
    "Black Swan (2010)",
    "The Social Network (2010)",
    "Gone Girl (2014)",
    "Zodiac (2007)",
    "The Curious Case of Benjamin Button (2008)",
    "The Girl with the Dragon Tattoo (2011)",
    "The Game (1997)",
    "The Panic Room (2002)",
    "The Lost World: Jurassic Park (1997)",
    "The Aviator (2004)",
    "The Departed (2006)",
    "The Irishman (2019)",
    "The Wolf of Wall Street (2013)",
    "Shutter Island (2010)",
    "The Revenant (2015)",
    "Birdman (2014)",
    "The Big Short (2015)",
    "The Social Network (2010)",
    "The Social Network (2010)",
  ],

  "Arriflex 235 (2-perf)": [
    "A Fistful of Dollars",
    "The Good, the Bad and the Ugly",
    "For a Few Dollars More",
    "Once Upon a Time in the West",
    "Duck, You Sucker!",
    "My Name Is Nobody",
    "A Genius, Two Partners and a Dupe",
    "The Grand Duel",
    "The Big Gundown",
    "Death Rides a Horse",
    "Day of Anger",
    "The Mercenary",
    "Companeros",
    "Keoma",
    "Mannaja",
    "The Great Silence",
    "The Hellbenders",
    "The Specialists",
    "The Price of Power",
    "The Forgotten Pistolero",
  ],
  "Aaton Penelope (2-perf)": [
    "American Graffiti",
    "The Conversation",
    "The French Connection",
    "The Exorcist",
    "The Sting",
    "The Towering Inferno",
    "The Poseidon Adventure",
    "The Taking of Pelham One Two Three",
    "The Parallax View",
    "The Day of the Jackal",
    "The Long Goodbye",
    "The Last Detail",
    "The Paper Chase",
    "The Friends of Eddie Coyle",
    "The Getaway",
    "The Candidate",
    "The Hot Rock",
    "The Heartbreak Kid",
    "The Godfather",
    "The Godfather: Part II",
    "The Godfather: Part III",
  ],

  "ARRI SR3": [
    "The Hurt Locker",
    "Moonrise Kingdom",
    "Carol",
    "The Social Network",
    "Gone Girl",
    "Zodiac",
    "The Curious Case of Benjamin Button",
    "The Girl with the Dragon Tattoo",
    "The Game",
    "The Panic Room",
    "The Lost World: Jurassic Park",
    "The Aviator",
    "The Departed",
    "The Irishman",
    "The Wolf of Wall Street",
    "Shutter Island",
    "The Revenant",
    "Birdman",
    "The Big Short",
    "The Social Network",
  ],
  "Aaton XTR Prod": [
    "The Hurt Locker",
    "Moonrise Kingdom",
    "Carol",
    "The Social Network",
    "Gone Girl",
    "Zodiac",
    "The Curious Case of Benjamin Button",
    "The Girl with the Dragon Tattoo",
    "The Game",
    "The Panic Room",
    "The Lost World: Jurassic Park",
    "The Aviator",
    "The Departed",
    "The Irishman",
    "The Wolf of Wall Street",
    "Shutter Island",
    "The Revenant",
    "Birdman",
    "The Big Short",
    "The Social Network",
  ],
  "Bolex H16": [
    "Carol",
    "The Social Network",
    "Gone Girl",
    "Zodiac",
    "The Curious Case of Benjamin Button",
    "The Girl with the Dragon Tattoo",
    "The Game",
    "The Panic Room",
    "The Lost World: Jurassic Park",
    "The Aviator",
    "The Departed",
    "The Irishman",
    "The Wolf of Wall Street",
    "Shutter Island",
    "The Revenant",
    "Birdman",
    "The Big Short",
    "Pulp Fiction",
    "Fight Club",
    "Se7en",
  ],

  "Canon 814 XL-S": [
    "Super 8",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
    "The Iron Claw",
    "The Bikeriders",
    "Guardians of the Galaxy Vol. 3",
    "The Suicide Squad",
    "The Matrix Resurrections",
    "Ambulance",
  ],
  "Nizo 801 Macro": [
    "Argo",
    "The Fighter",
    "The Gray Man",
    "The Adam Project",
    "The Tomorrow War",
    "Barbie",
    "Poor Things",
    "Saltburn",
    "Oppenheimer",
    "The Zone of Interest",
    "Maestro",
    "The Holdovers",
    "May December",
    "Asteroid City",
    "Past Lives",
    "The Killer",
    "Ferrari",
    "The Color Purple",
    "The Iron Claw",
    "The Bikeriders",
  ],

  "Logmar Super 8": ["Super 8"],
  "Kodak Super 8 Camera": ["Super 8"],
};
