export const CAMERAS: Record<string, string[]> = {
  "IMAX 65mm (15-perf)": ["IMAX MSM 9802", "IMAX MKIII", "IMAX MSM 870"],
  "65mm (5-perf)": ["ARRIFLEX 765", "Panavision System 65", "Mitchell FC"],
  "VistaVision (35mm 8-perf)": [
    "Mitchell VistaVision",
    "ILM VistaVision (modified)",
  ],
  "35mm 4-perf (Academy)": [
    "ARRICAM ST",
    "ARRICAM LT",
    "Arriflex 435",
    "Panavision Millennium XL2",
  ],
  "35mm 3-perf": ["ARRICAM LT (3-perf gate)", "Aaton Penelope"],
  "35mm 2-perf (Techniscope)": [
    "Arriflex 235 (2-perf)",
    "Aaton Penelope (2-perf)",
  ],
  "Super 16": ["ARRI SR3", "Aaton XTR Prod", "Bolex H16"],
  "Super 8 (regular gate)": ["Canon 814 XL-S", "Nizo 801 Macro"],
  "Super 8 (extended gate)": ["Logmar Super 8", "Kodak Super 8 Camera"],
  "ARRI ALEXA 65 (Open Gate)": ["ARRI ALEXA 65"],
  "ARRI ALEXA LF / Mini LF (Open Gate)": [
    "ARRI ALEXA LF",
    "ARRI ALEXA Mini LF",
  ],
  "ARRI ALEXA 35 (Open Gate 3:2)": ["ARRI ALEXA 35"],
  "RED V-RAPTOR 8K VV": ["RED V-RAPTOR 8K VV"],
  "RED MONSTRO 8K VV": ["RED MONSTRO 8K VV"],
  "RED KOMODO 6K (S35)": ["RED KOMODO 6K"],
  "Sony VENICE 2 (8.6K FF, Open Gate)": ["Sony VENICE 2"],
  "Canon EOS C500 Mark II (FF DCI area)": ["Canon EOS C500 Mark II"],
  "Canon EOS C300 (Super 35)": ["Canon EOS C300 Mark III"],
  "Blackmagic URSA Mini Pro 12K (S35)": ["Blackmagic URSA Mini Pro 12K"],
  "Blackmagic Pocket Cinema Camera 6K (S35)": ["Blackmagic Pocket 6K Pro"],
  "Panasonic VariCam 35 (S35)": ["Panasonic VariCam 35"],
  "Full Frame (35mm still)": ["Canon EOS R5C", "Sony FX3", "Nikon Z9 (video)"],
  "APS-C (typical)": ["Canon C70", "Sony FS7", "BMPCC 6K (crop modes)"],
  "Micro Four Thirds": [
    "Panasonic GH6",
    "Blackmagic Pocket 4K",
    "Olympus OM-D",
  ],
  'Type 1" (1-inch)': ["Sony RX100 series", "Canon G7X series"],
};
